package lpsolvematrix;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lp_matrix.h:2535</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DeltaVrec extends Structure {
	/** C type : lprec* */
	public lpsolvelib.lprec.ByReference lp;
	public int activelevel;
	/** C type : MATrec* */
	public lpsolvematrix.MATrec.ByReference tracker;
	public DeltaVrec() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("lp", "activelevel", "tracker");
	}
	/**
	 * @param lp C type : lprec*<br>
	 * @param tracker C type : MATrec*
	 */
	public DeltaVrec(lpsolvelib.lprec.ByReference lp, int activelevel, lpsolvematrix.MATrec.ByReference tracker) {
		super();
		this.lp = lp;
		this.activelevel = activelevel;
		this.tracker = tracker;
	}
	public static class ByReference extends DeltaVrec implements Structure.ByReference {
		
	};
	public static class ByValue extends DeltaVrec implements Structure.ByValue {
		
	};
}
