package lpsolvetypes;
import com.sun.jna.Structure;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lp_types.h:2263</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class B4rec extends Structure {
	/**
	 * Position of basic columns in the B4 basis<br>
	 * C type : int*
	 */
	public IntByReference B4_var;
	/**
	 * Variable in the B4 basis<br>
	 * C type : int*
	 */
	public IntByReference var_B4;
	/**
	 * B4 position of the i'th row<br>
	 * C type : int*
	 */
	public IntByReference B4_row;
	/**
	 * Original position of the i'th row<br>
	 * C type : int*
	 */
	public IntByReference row_B4;
	/** C type : double* */
	public DoubleByReference wcol;
	/** C type : int* */
	public IntByReference nzwcol;
	public B4rec() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("B4_var", "var_B4", "B4_row", "row_B4", "wcol", "nzwcol");
	}
	/**
	 * @param B4_var Position of basic columns in the B4 basis<br>
	 * C type : int*<br>
	 * @param var_B4 Variable in the B4 basis<br>
	 * C type : int*<br>
	 * @param B4_row B4 position of the i'th row<br>
	 * C type : int*<br>
	 * @param row_B4 Original position of the i'th row<br>
	 * C type : int*<br>
	 * @param wcol C type : double*<br>
	 * @param nzwcol C type : int*
	 */
	public B4rec(IntByReference B4_var, IntByReference var_B4, IntByReference B4_row, IntByReference row_B4, DoubleByReference wcol, IntByReference nzwcol) {
		super();
		this.B4_var = B4_var;
		this.var_B4 = var_B4;
		this.B4_row = B4_row;
		this.row_B4 = row_B4;
		this.wcol = wcol;
		this.nzwcol = nzwcol;
	}
	public static class ByReference extends B4rec implements Structure.ByReference {
		
	};
	public static class ByValue extends B4rec implements Structure.ByValue {
		
	};
}
