package lpsolvetypes;
import com.sun.jna.Structure;
import com.sun.jna.ptr.DoubleByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lp_types.h:2294</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class edgerec extends Structure {
	/** C type : double* */
	public DoubleByReference edgeVector;
	public edgerec() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("edgeVector");
	}
	/** @param edgeVector C type : double* */
	public edgerec(DoubleByReference edgeVector) {
		super();
		this.edgeVector = edgeVector;
	}
	public static class ByReference extends edgerec implements Structure.ByReference {
		
	};
	public static class ByValue extends edgerec implements Structure.ByValue {
		
	};
}
